### ISSUE TITLE
prompt_principal not parsed as pam argument

### ISSUE THREAD

**Issue by jcpunk** [rra/pam-krb5#5]
Version: pam_krb5 4.7 (self built rpm)
OS: Scientific Linux 6

When I set `prompt_principal = true` in `/etc/krb5.conf`, I am prompted as expected.

However, when I omit `prompt_principal` from the config file and set it as a PAM argument I am not prompted.  Is there a specific way this argument should be passed in?

content of `/etc/pam.d/system-auth` (imported by the actual login process)
```
auth        required      pam_env.so
auth        [success=3 default=ignore] pam_succeed_if.so service notin login:gdm:xdm:kdm:xscreensaver:gnome-screensaver:kscreensaver quiet use_uid
auth        [success=ok authinfo_unavail=2 ignore=2 default=die] pam_pkcs11.so card_only
auth        optional      pam_krb5.so debug=true	prompt_principal
auth        sufficient    pam_permit.so
auth        sufficient    pam_fprintd.so
auth        sufficient    pam_unix.so nullok try_first_pass
auth        requisite     pam_succeed_if.so uid >= 500 quiet
auth        sufficient    pam_krb5.so
auth        required      pam_deny.so
```

**Comment by rra** [comment]
I'm fairly certain that this works when passed as a PAM parameter.  There are tests specifically for that.  I'm not sure why it's not working for you, but I did notice that you have a tab instead of a space before `prompt_principal` in the configuration file you provided.  Maybe your PAM library doesn't like tabs in the argument list for the PAM module?  That would surprise me a bit, but I don't have another good explanation.

(Well, I'll note that prompt_principal only does something if you're prompting, and normally if the PAM module isn't the first module in the auth stack it uses the stored password and doesn't prompt, but presumably you're working around that or `pam_pkcs11.so` doesn't prompt if you're seeing prompts with the `krb5.conf` configuration.)

**Comment by jcpunk** [comment]
Interesting, I've tried switching out tab and space to no avail.  Is there a setting I can use to get a deeper insight into the runtime of pam_krb5?  I'm beginning to be suspicious that I'm passing in the argument wrongly and would love to see what the module thinks its arguments are.  Alas my PAM debugging knowledge is near zero.

**Comment by jcpunk** [comment]
Got it sorted, short version of debugging:

- recompile pam with debug mode
- extract all argv creation for pam_krb5.so

Turns out the `sufficient` module should have the argument not the `optional` invocation.
